POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
    "name": "nguyen thanh dat",
    "email": "nguyenthanhdat22012001@gmail.com",
    "password": "123456789",
    "confirm_password": "123456789"
}
###
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "email": "namlan@gmail.com",
    "password": "123456789"
}
###
POST http://127.0.0.1:8000/api/forgot-password
Content-Type: application/json

{
    "email": "nguyenthanhdat22012001@gmail.com"
}
###
POST http://127.0.0.1:8000/api/admin/login
Content-Type: application/json

{
    "email": "tieuviem@gmail.com",
    "password": "tieuviem123"
}
###
POST http://127.0.0.1:8000/api/stores
Content-Type: application/json

{
    "img": "",
    "user_id": 1,
    "name": "nam ha",
    "address": "ádasdasd",
    "phone": 3453456456
}

# post
###
GET http://127.0.0.1:8000/api/posts
Content-Type: application/json
###
POST http://127.0.0.1:8000/api/posts
Content-Type: application/json

{
    "user_id": 1,
    "name": "nam Ha",
    "description": ""
}
###
GET  http://127.0.0.1:8000/api/posts/toi-day
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/like-post
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 2
}
###
POST http://127.0.0.1:8000/api/posts/disk-like-post
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 2
}
###
GET http://127.0.0.1:8000/api/check-user-like-post?user_id=1&post_id=2
Content-Type: application/json


# comment post
###
POST http://127.0.0.1:8000/api/posts_comment
Content-Type: application/json

{
    "user_id": 1,
    "post_id": 2,
    "comment": "ma la ka ma la kana mama",
    "parent_id": 2
}
###
GET http://127.0.0.1:8000/api/posts_comment/2
Content-Type: application/json

###
GET http://127.0.0.1:8000/api/product/detail/1kg-lap-xuong-tom-dac-san-soc-trang-lap-xuong-tom-loai-ngon-dac-biet-tpfood-bach-hoa-online
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/product/category/thoi-trang
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/product/store/nguyen-dat
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/product/comments/9
Content-Type: application/json
###
GET http://127.0.0.1:8000/api/coupons
Content-Type: application/json
#collection coupon
###
POST http://127.0.0.1:8000/api/collection-coupon
Content-Type: application/json

{
    "user_id": 2,
    "coupon_id": 1
}
###
GET http://127.0.0.1:8000/api/collection-coupon/user/2
Content-Type: application/json

###
DELETE  http://127.0.0.1:8000/api/collection-coupon/1
Content-Type: application/json

#collection product
###
POST http://127.0.0.1:8000/api/collection-product
Content-Type: application/json

{
    "user_id": 2,
    "product_id": 8
}
###
GET http://127.0.0.1:8000/api/collection-product/user/2
Content-Type: application/json

###
DELETE  http://127.0.0.1:8000/api/collection-product/1
Content-Type: application/json


#collection store
###
POST http://127.0.0.1:8000/api/collection-store
Content-Type: application/json

{
    "user_id": 2,
    "store_id": 2
}
###
GET http://127.0.0.1:8000/api/collection-store/user/2
Content-Type: application/json

###
DELETE  http://127.0.0.1:8000/api/collection-store/1
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/add-to-cart
Content-Type: application/json

{
    "product_id": 8,
    "attribute_id": 4,
    "qty": 1
}

###
GET http://127.0.0.1:8000/api/admin/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9hZG1pblwvbG9naW4iLCJpYXQiOjE2MzY2MTY5MzEsImV4cCI6MTYzNjYxNjk5MSwibmJmIjoxNjM2NjE2OTMxLCJqdGkiOiJUZjVLTlJtT0RHR25VOEdOIiwic3ViIjoyLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.ePKRkoBI4mWSkf5ceA3F1Z86UiIneLEXLCC-RIYhYKk